Create Sponsor Logos Partial
c2pa-org/c2pa-org.github.io pull request #25
Opened 2021-04-05 15:51 UTC by jorydotcom

This PR creates a partial layout for member logos to easily extent the logos displayed on our home page. When a new member joins we will just need to upload their logo to /static/images/sponsor-logos to have it flexibly displayed on the site.

PR also includes a chore - add .ds_store to gitignore.

2021-04-05 16:08 UTC, lrosenthol requested changes
just push up the built versions and we should be good...thanks!

2021-04-06 19:29 UTC, lrosenthol requested changes

2021-04-06 19:29 UTC, lrosenthol commented on docs/404.html
> +  <head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>
Did you do a build or a serve?  these look like the serve files with the refs to livereload and locahost!

2021-04-15 13:34 UTC, jorydotcom commented
Per email exchange with Adobe team, closing as the new site will launching very soon with a different approach!! 🎉 🎉 🎉 🎉

2021-04-15 13:34 UTC, closed without merging